apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-service
  description: The Sample Service API allows you to send errors to Rollbar or Sentry.
  tags:
    - unstable
spec:
  type: openapi
  lifecycle: production
  owner: info@roadie.io
  definition: |
    openapi: "3.0.3"
    info:
      title: The Sample Service API
      version: 0.0.1
      description: Send errors to Rollbar or Sentry

    servers:
      - url: http://localhost:7000/api/proxy/json/
        description: A plublic instance which anyone can hit to generate sample data.

    paths:
      /issues:
        get:
          summary: Return all undecorated issues
          responses:
            '200':
              description: A JSON object with a message key and Hello World value.
              content:
                application/json:
                  schema:
                    type: object
                    example:
                      message: Hello world!

      /comments:
        get:
          summary: Return all comments
          responses:
            '200':
              description: A JSON object with a message key and Hello World value.
              content:
                application/json:
                  schema:
                    type: object
                    example:
                      message: Hello world!

      /projects:
        get:
          summary: Return all comments
          responses:
            '200':
              description: A JSON object with a message key and Hello World value.
              content:
                application/json:
                  schema:
                    type: object
                    example:
                      message: Hello world!
      /db:
        get:
          summary: Return all comments
          responses:
            '200':
              description: A JSON object with a message key and Hello World value.
              content:
                application/json:
                  schema:
                    type: object
                    example:
                      message: Hello world!


          responses:
            '200':
              description: Confirmation that the error was sent.
              content:
                application/json:
                  schema:
                    type: object
                    example:
                      message: 'Error sent to Rollbar: "My first error"'
