apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: martina-service
  description: |
    A service for testing basic entities
  annotations:
    cloud.google.com/function-ids: projects/backstage-test-project/locations/us-central1/functions/helloMarek
    travis-ci.com/repo-slug: RoadieHQ/sample-service 
spec:
  type: service
  owner: martina@roadie.io
  lifecycle: experimental
