---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  annotations:
    github.com/project-slug: martina-if/sample-service
spec:
  type: other
  lifecycle: unknown
  owner: 'user:iain@roadie.io'
