apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-5
  description: |
    A service for testing Backstage functionality. Configured for GitHub Actions and
    Sentry.
  annotations:
    circleci.com/project-slug: github/martina-if/CircleCITEst
    # The Sentry organization is stored in the app-config.yaml of the Backstage instance.
    sentry.io/project-slug: sample-service
    backstage.io/techdocs-ref: dir:./
    pagerduty.com/integration-key: 1cf15c07f6f440e0a8d65b7ce80be834
spec:
  type: service
  owner: dtuite
  lifecycle: experimental
  implementsApis:
    - sample-service
